name: OpenTofu Install
description: Install OpenTofu CLI tool with caching support

inputs:
  tofu_version:
    description: OpenTofu version to install (e.g. 1.8.0)
    required: false
    default: 1.8.0

outputs:
  tofu_version:
    description: Installed OpenTofu version
    value: ${{ steps.verify.outputs.tofu_version }}
  cache_hit:
    description: Whether OpenTofu was restored from cache (true/false)
    value: ${{ steps.cache-tofu.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Install OpenTofu
      if: steps.cache-tofu.outputs.cache-hit != true
      shell: bash
      env:
        TOFU_VERSION: ${{ inputs.tofu_version }}
      run: bash ${{ github.action_path }}/../../scripts/opentofu-install.sh
