name: OpenTofu Install
description: Install OpenTofu CLI

inputs:
  tofu_version:
    description: OpenTofu version to install
    required: false
    default: 1.8.0

runs:
  using: composite
  steps:
    - name: Cache OpenTofu
      id: cache-tofu
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/tofu
        key: opentofu-${{ runner.os }}-${{ inputs.tofu_version }}

    - name: Install OpenTofu
      if: steps.cache-tofu.outputs.cache-hit != true
      shell: bash
      env:
        TOFU_VERSION: ${{ inputs.tofu_version }}
      run: |
        bash ${{ github.action_path }}/../../scripts/opentofu-install.sh

    - name: Verify OpenTofu
      shell: bash
      run: tofu version
