name: 'OpenTofu Install'
description: 'Install OpenTofu CLI'
runs:
  using: 'composite'
  steps:
    - name: Install OpenTofu
      shell: bash
      run: |
        bash ${{ github.action_path }}/../../scripts/opentofu-install.sh
