name: OpenTofu Init
description: Initialize OpenTofu working directory
inputs:
  target_path:
    description: Path to OpenTofu configuration directory
    required: false
    default: ./infrastructure
runs:
  using: composite
  steps:
    - name: Initialize OpenTofu
      shell: bash
      run: |
        bash ${{ github.workspace }}/.github/scripts/opentofu-init.sh "${{ inputs.target_path }}"
