name: OpenTofu Init
description: Initialize OpenTofu working directory and download providers

inputs:
  working_directory:
    description: Absolute or relative path to the OpenTofu configuration directory
    required: true
  state_key:
    description: State file key for backend configuration
    required: true

runs:
  using: composite
  steps:
    - name: Initialize OpenTofu
      id: init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        bash ${{ github.workspace }}/.github/scripts/opentofu-init.sh "${{ inputs.state_key }}"
