name: 'OpenTofu Plan'
description: 'Generate and show OpenTofu execution plan'
inputs:
  target_path:
    description: 'Path to OpenTofu configuration directory'
    required: false
    default: './infrastructure'
  var_file:
    description: 'Path to variables file'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Plan OpenTofu changes
      shell: bash
      run: |
        bash ${{ github.action_path }}/../../scripts/opentofu-plan.sh "${{ inputs.target_path }}" "${{ inputs.var_file }}"
