name: OpenTofu Plan
description: Generate and show OpenTofu execution plan
inputs:
  target_path:
    description: Path to OpenTofu configuration directory
    required: false
    default: ./infrastructure
  var_file:
    description: Path to variables file
    required: false
    default:
outputs:
  plan_file:
    description: Path to the plan text output file
    value: ${{ steps.plan.outputs.plan_file }}
  plan_binary_file:
    description: Path to the binary plan file for apply
    value: ${{ steps.plan.outputs.plan_binary_file }}
runs:
  using: composite
  steps:
    - name: Plan OpenTofu changes
      id: plan
      shell: bash
      run: |
        bash ${{ github.workspace }}/.github/scripts/opentofu-plan.sh "${{ inputs.target_path }}" "${{ inputs.var_file }}"
