name: OpenTofu PR Comment
description: Post OpenTofu plan output as a PR comment
inputs:
  plan_file:
    description: Path to file containing plan output
    required: true
  environment:
    description: Environment name
    required: false
    default: dev
  target_path:
    description: Path to OpenTofu configuration directory
    required: false
    default: ./environments/dev
runs:
  using: composite
  steps:
    - name: Generate comment body
      id: comment
      shell: bash
      run: |
        bash ${{ github.workspace }}/.github/scripts/opentofu-pr-comment.sh "${{ inputs.plan_file }}" "${{ inputs.environment }}" "${{ inputs.target_path }}"

    - name: Find existing comment
      id: find-comment
      uses: peter-evans/find-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: github-actions[bot]
        body-includes: OpenTofu Plan

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.comment.outputs.comment_body }}
        edit-mode: replace
