name: OpenTofu Apply
description: Apply OpenTofu configuration changes
inputs:
  target_path:
    description: Path to OpenTofu configuration directory
    required: false
    default: ./infrastructure
  plan_file:
    description: Path to the binary plan file to apply
    required: true
runs:
  using: composite
  steps:
    - name: Apply OpenTofu changes
      shell: bash
      run: |
        bash ${{ github.workspace }}/.github/scripts/opentofu-apply.sh "${{ inputs.target_path }}" "${{ inputs.plan_file }}"
